security:
  basic:
    enabled: false
    
spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/spring_oauth;INIT=runscript from'classpath:schema-h2.sql'\;runscript from 'classpath:data-h2.sql'
    name: spring_oauth
    username: root
    password: 
    initialize: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: true
  h2:
    console:
      enabled: true
      